# Generated by Django 3.2.5 on 2022-03-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemessage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemessage',
            name='numberoflike',
            field=models.IntegerField(default=0),
        ),
    ]
