# Generated by Django 3.2.5 on 2022-03-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemessage', '0002_leavemessage_numberoflike'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemessage',
            name='openid',
            field=models.TextField(default='000000', max_length=50),
        ),
    ]
