# Generated by Django 3.2.5 on 2022-03-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemessage', '0003_leavemessage_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemessage',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
