# Generated by Django 3.2.5 on 2022-03-20 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leavemessage', '0004_leavemessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavemessage',
            name='content',
        ),
    ]
