# Generated by Django 3.2.5 on 2022-03-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemessage', '0005_remove_leavemessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemessage',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
