# Generated by Django 3.2.5 on 2022-03-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemessage', '0006_leavemessage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemessage',
            name='content',
            field=models.TextField(max_length=150, null=True),
        ),
    ]
