# Generated by Django 3.2.5 on 2022-03-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiezi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('grade', models.IntegerField()),
                ('faculty', models.IntegerField()),
                ('numberofcollect', models.IntegerField()),
                ('numberoflike', models.IntegerField()),
                ('numberofpost', models.IntegerField()),
                ('openid', models.TextField(max_length=100)),
                ('photopaths', models.ImageField(null=True, upload_to='headpic')),
                ('selftext', models.TextField(max_length=100)),
                ('sex', models.TextField(max_length=5)),
                ('tiezi', models.ManyToManyField(to='tiezi.tiezi')),
            ],
        ),
    ]
