# Generated by Django 3.2.5 on 2022-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='tiezi',
        ),
        migrations.AddField(
            model_name='people',
            name='collecttiezi',
            field=models.ManyToManyField(related_name='collectpeople', to='tiezi.tiezi'),
        ),
        migrations.AddField(
            model_name='people',
            name='liketiezi',
            field=models.ManyToManyField(related_name='likepeople', to='tiezi.tiezi'),
        ),
    ]
