# Generated by Django 3.2.5 on 2022-03-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavemessage', '0003_leavemessage_openid'),
        ('login', '0002_auto_20220306_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='likeleavemessage',
            field=models.ManyToManyField(to='leavemessage.leavemessage'),
        ),
    ]
