# Generated by Django 3.2.5 on 2022-03-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_people_likeleavemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='content',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
