# Generated by Django 3.2.5 on 2022-03-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_people_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='text',
            field=models.TextField(max_length=120, null=True),
        ),
    ]
