# Generated by Django 3.2.5 on 2022-03-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leavemessage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tiezi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('numoflike', models.IntegerField()),
                ('numofcollect', models.IntegerField()),
                ('kind', models.BooleanField()),
                ('openid', models.TextField(max_length=100)),
                ('ownid', models.TextField(max_length=100)),
                ('onshow', models.BooleanField(default=True)),
                ('leavemessage', models.ManyToManyField(to='leavemessage.leavemessage')),
            ],
        ),
    ]
