# Generated by Django 3.2.5 on 2022-03-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiezi',
            name='name',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
