# Generated by Django 3.2.5 on 2022-03-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0002_tiezi_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiezi',
            name='havecollect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tiezi',
            name='havelike',
            field=models.BooleanField(default=False),
        ),
    ]
