# Generated by Django 3.2.5 on 2022-03-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0004_tiezi_numofleavemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiezi',
            name='havecollect',
        ),
        migrations.RemoveField(
            model_name='tiezi',
            name='havelike',
        ),
    ]
