# Generated by Django 3.2.5 on 2022-03-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0005_auto_20220320_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiezi',
            name='havecollect',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='tiezi',
            name='havelike',
            field=models.BooleanField(null=True),
        ),
    ]
