# Generated by Django 3.2.5 on 2022-03-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0006_auto_20220320_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiezi',
            name='havecollect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tiezi',
            name='havelike',
            field=models.BooleanField(default=False),
        ),
    ]
