# Generated by Django 3.2.5 on 2022-04-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiezi', '0007_auto_20220320_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiezi',
            name='isqa',
            field=models.BooleanField(default=False),
        ),
    ]
